DropOnCreative: false
UseOnCreative: false
UsePermission: "colorblock.use"
AdminPermission: "colorblock.admin"
ConfigReloaded: "Config reloaded"
PermissionError: "Insufficient permissions"
WrongArgsError: "Wrong or insufficient arguments"