###################################################
#                                                 #
#                ColorBlock2 Config               #
#                                                 #
###################################################

#Hooks for various protection plugins
WorldGuardHook: false
LandsHook: false

#Drop option indicates whether old dye of block drops when coloring block
DropOnCreative: false
DropOnSurvival: true
#Use option indicates whether new dye gets consumed when coloring block
#Recommended to set both things to same values to avoid creating infinite dye exploit
UseOnCreative: false
UseOnSurvival: true

#Allows you to customize permissions
DyePermission: "colorblock.dye"
UndyePermission: "colorblock.undye"
AdminPermission: "colorblock.admin"

#Allows You to customize in-game messages. Hex color codes or classic color codes are supported
ConfigReloaded: "#3A9C20Config reloaded#31E900"
PermissionError: "#AB4C37Insufficient permissions#FF0101"
WrongArgsError: "#AB4C37Wrong or insufficient arguments#FF0101"
PluginPrefix: "#D80F52[ColorBlock2] #30D3F3"

#Allows you to set sound that will be transmitted when dyeing a block. Set to "NONE" to disable
ColorSound: "BLOCK_BAMBOO_HIT"
#Volume indicates how far away sound will be heard. 5.0 means it will be heard from 5 blocks away
ColorVolume: 5.0

UncolorSound: "BLOCK_SOUL_SAND_BREAK"
UncolorVolume: 5.0

#Allows you to set Particle effects when dyeing or undyeing a block. Set to "NONE" to disable
ColorParticle: "FIREWORKS_SPARK"
UncolorParticle: "CRIT"

#Particle Chance of appearing, 0 to 100
#0 to disable, 100 = all 27 particles
ParticleChance: 50